# Code of conduct

We are committed to creating an inclusive environment for everyone, regardless of race, ethnicity, religion, color, national origin, age, disability (physical or mental), sexual orientation, gender identity, parental status, marital status, and political affiliation as well as gender expression, mental illness, socioeconomic status or background, neuro(a)typicality, or physical appearance. Our community is built upon a set of values that includes trust, empathy, and mutual respect, and we celebrate our unique differences.

Like emLab’s core values, the contents of this code of conduct are concepts we expect teammates to work to apply to their daily lives. Specifically, the code of conduct applies to teammate interactions in various areas of our shared professional lives, including within emLab offices, meetings, emLab events, shared online spaces (Slack, email, etc.), social media, conferences, working groups, and other meetings and/or events where we represent emLab.

We believe that articulating our values and accountabilities reinforces the respect we have for one another and our commitment to an inclusive workplace, and provides us with clear avenues to correct our culture should it ever stray. Our code of conduct is a living document and we commit to enforcing and updating this code as our team evolves over time. 

**Expected behaviors**

Every member of the emLab team is expected to support each other and contribute to a collaborative, positive, and healthy environment in which we can all succeed. Specifically:

- **Be supportive and collaborative.** Make time for each other: generously share and seek out knowledge, advice, and resources from each other. Engage with your teammates in brainstorming sessions, troubleshooting code, editing reports, and general problem solving. We are a diverse team with a variety of expertise, so it is always acceptable and encouraged to ask questions. Good teamwork is characterized by open and honest communication, transparency, mutual respect and accountability, and trust. Elevate each other, acknowledge and highlight others’ work and ideas, and give credit where credit is due.

- **Be inclusive.** Actively seek and collaborate with people of diverse perspectives. Be respectful of people with different cultural practices, attitudes, and beliefs. Actively work to eliminate your own biases, prejudices, and discriminatory practices. Use preferred titles and pronouns. Value each other’s ideas, styles, and viewpoints. 

- **Be self-aware and self-teaching.** Make it your responsibility to come to meetings prepared, to note down the things you aren’t familiar with, and to brush up on the things you hear about that are relevant to your teams and projects. A supportive and encouraging culture works best when everyone is proactive and entrepreneurial in finding the resources and skills they need. This extends to our personal interactions as well: make it your responsibility to educate yourself on the social issues or topics that impact your colleagues (list of resources below). 	

- **Be open and generous in giving and accepting feedback.** Good feedback is kind, respectful, clear, constructive, and focused on goals and values rather than personal preferences. You are expected to give and receive feedback with gratitude and a growth mindset. 

- **Be kind.** We expect all community members to treat each other with empathy and respect. Be kind to yourself as well – don’t succumb to impostor syndrome; you are here because you deserve to be here. Be polite and considerate in all forms of communication – especially remote communication, where opportunities for misunderstanding are greater.

**Unacceptable behaviors**

We are committed to providing a welcoming and safe environment for all. Discrimination and harassment are expressly prohibited. Harassment can be overtly physical, including [sexual harassment](https://titleix.ucsb.edu/about/sexual-harassment-sexual-violence), but it can also come in the form of speech or behavior that is not welcome or is personally offensive. Harassment or unwelcome behavior or language intended in a joking manner still constitutes unacceptable behavior. Be mindful of the words that you choose, even if it’s as small as choosing “hey, everyone” over “hey, guys.” Sexist, racist, ableist, and other exclusionary jokes or comments are inappropriate and will not be tolerated under any circumstance. 

Furthermore, any behavior or language that is unwelcoming—whether or not it rises to the level of harassment—is unacceptable. There are certain behaviors and language common in academia which are worth noting as specifically unacceptable:

- **No acts of prejudice, no matter how subtle.** Exclusionary behavior often takes the form of subtle -isms, which can be both verbal and nonverbal abuse and are often the manifestation of unconscious (or implicit) bias. For example, saying “It’s so easy my grandmother could do it” is a subtle -ism with tones of both sexism and ageism. Regardless of intent, these comments can have a significant demeaning impact on teammates.

- **No condescension.** It’s never ok to diminish other people’s perspectives. Unwelcome interruptions, answering on behalf of others, talking over people, and giving unsolicited advice or direction in a condescending manner are common problems that stem from a systemic inequality of access to and validation of knowledge within the academic community. The difference between being helpful and being condescending hinges on the words you choose and whether or not you have been actively listening.

This is not an exhaustive list. Behavior that is acceptable to one person may not be acceptable to another, so use discretion to be certain respect is communicated. 

**Reporting a problem**

These guidelines are ambitious, and we’re not always going to succeed in meeting them. If you experience or witness unacceptable behavior—whether it’s subtle abuse or an instance of harassment—we want to make sure it is addressed. 

- **Talk to a member of the diversity, equity, and inclusion (DEI) team.** We are open to concerns about situations of any size and magnitude, and we take these concerns seriously. You can make a report either personally or anonymously through [this google form](https://docs.google.com/forms/d/e/1FAIpQLSevcBTkEq6mM6-pPZnqpE4nXPJ_GA40R1GmNH1KRo5SrADquw/viewform?usp=sf_link). In all cases, we will make every effort to stay in clear communication with anyone who reports a problem, maintaining confidentiality requests as much as possible for the purpose of protecting victims of abuse in accordance with University Policies. This may include reporting the incident to the [UCSB Title IX & Sexual Harassment Policy Compliance Office](https://titleix.ucsb.edu/) or to the [UCSB Equal Opportunity & Discrimination Prevention Office](https://oeosh.ucsb.edu/eodp/).

- **Talk to your supervisor.** Your supervisor should know about the dynamics of your team, making them a good person to contact for advice. They should be able to talk directly to the colleague in question if you feel uncomfortable or unsafe doing so yourself. Finally, your supervisor will be able to help you figure out how to ensure that any conflict with a colleague doesn’t interfere with your work.

- **Address it directly.** For smaller incidents that might be settled with a brief conversation, you can choose to email or slack the person directly or set up a meeting to discuss how it affected you. Please use this approach only if you feel comfortable; you do not have to carry the weight of addressing these issues yourself. If you’re interested in this option but unsure how to go about it, you can reach out to your supervisor or a member of the DEI team first for advice.

**Code violations**

Repeated or severe violations of this code can and will be addressed by the emLab Leadership Team, and can lead to disciplinary actions that scale to the severity of the violation, including termination.

**Taking care of each other**

If you ever witness something that seems like it isn’t aligned with our values or these standards, err on the side of caring for your colleagues. Even if an incident seems minor, reach out to the person impacted by it to check in. We would also appreciate it if you would speak to your supervisor or a member of the DEI team directly to voice your concerns. Depending on the circumstances, you may also want to speak directly to the person who has violated our standards.

If you want to speak to a person impacted by an incident or to the person who has violated the code of conduct, but you’re unsure of how to navigate these interactions, we encourage you to reach out to your supervisor or a member of the DEI team — these conversations are tricky, and we would like to help you figure out how best to approach them.

**Committing to self-improvement**

We are committed to owning up to our mistakes and continuously working to improve. If you are approached as having acted in a way that might make your teammates feel unwelcome, listen with an open mind and avoid becoming defensive. Remember that if someone offers you feedback, it likely took a great deal of courage for them to do so. The best way to respect that courage is to listen carefully, acknowledge your mistake, apologize sincerely, and correct the behavior going forward.

**Resources**

- [emLab #ShutDownAcademia Library](https://docs.google.com/spreadsheets/d/1TUNh3xLyZBpnJwXLhvty2K6L6wvQxoCmJMOy1ChTMRY/edit#gid=0)

- Online resources and books

  - [Racial Equity Tools](https://www.racialequitytools.org/home)
  
  - [Nonprofit Leadership Alliance DEI Resource Library](https://www.nonprofitleadershipalliance.org/dei-resource-library)
  
  - [Radical Candor](https://www.radicalcandor.com/6-tips-helpful-feedback/)
  
  - [Crucial Conversations](https://athlosacademies.org/top-10-takeaways-from-crucial-conversations/)
  
  - [Personal pronouns](https://www.mypronouns.org/what-and-why)
  
- University trainings (web-based)

  - [Managing Diversity - Organization](https://www.learningcenter.ucsb.edu/training-courses/managing-diversity-organization)

  - [Managing Diversity - Individual](https://www.learningcenter.ucsb.edu/training-courses/managing-diversity-individual)
  
  - [Appreciating Diversity](https://www.learningcenter.ucsb.edu/training-courses/appreciating-diversity)

  - More online videos and courses are available through [Linkedin Learning](https://www.linkedin.com/learning/me?u=57119945). Note: Access is free with your university log-in. 

*Our Code of Conduct is heavily drawn from [Buffer](https://open.buffer.com/code-of-conduct/), [Vox Media](https://code-of-conduct.voxmedia.com/?_ga=1.62865454.308680892.1455143920), and [Openscapes](https://www.openscapes.org/code-of-conduct/); we appreciate their leadership and pioneering efforts to openly share and encourage the widespread adoption of Codes of Conduct.*

