---
title: "Expectations"
output: html_document
---
# Expectations

## Work environment

**Principles for creating a hybrid schedule for emLab**

We are excited for emLab to adopt a hybrid schedule starting this fall so that the emLab community can use campus and our offices as a tool for supporting connection, community and [culture](https://emlab-ucsb.github.io/emlab-manual/emlab-values-and-culture.html#emlab-culture) across our team. In thinking about what kind of working model and balance between remote and in-person work would best support the emLab community, we considered our mission, values and culture, learned from the hybrid pilots over the past year and used data and information about hybrid and remote work (e.g., Adam Grant’s [podcast](https://www.ted.com/podcasts/worklife/the-do-s-and-don-ts-of-returning-to-the-office-transcript)). 

One of emLab’s main goals is to build a vibrant intellectual community of people to collaborate on innovative, impactful research. As a team who iterates together on ideas, research, writing and coding, spending time together in the office is important to support this flow of ideas and information. We each balance both team oriented activities and tasks with individual tasks, so having time to focus on individual work is also important. We provide guidance below on the structure of the hybrid schedule, and realize that remaining flexible and adapting as needed is essential as we all try to navigate this phase of pandemic life together in the best way possible.

**Overview of the hybrid model**

- emLab will return to in-person work starting the week of September 12.
- All Santa Barbara-based team members will be expected to work from campus Tuesday - Wednesday and have the option to work remotely Monday, Thursday, and Friday.
  - Take advantage of in person/on campus days for things like: internal team meetings, structured and unstructured time with your project teams, brainstorming sessions, walking and running meetings, collaborative writing, working sessions, troubleshooting with colleagues, white board sessions, etc.
  - Take advantage of remote days for things like: focused work, ‘deep’ work, coding, focused writing, 1:1 meetings that don’t fit in other days, etc
- All Santa Barbara-based team members will have [assigned office space](https://docs.google.com/document/d/1_VZPN_Ecz0ylSm6DJhV-pNkTGzA-G3FKOh-bqx2lm-8/edit) on the UCSB campus.

**Logistics**

*Meetings*

- All-team meetings and events will take place on in-person team days
  - emLab’s “MMM” will move to Tuesdays from 9:30 -10 am - now called emLab Tuesday Team Time (TTT)
  - emLab watercoolers will be held on Wednesdays or Thursdays
  - emLab/Environmental Resource Economics (ERE) seminars will be held on Thursdays
  - emLab lunches are returning in a new form - this will be a casual, informal time to have lunch and catch up with colleagues on Decker’s Deck. *Note: emLab lunches will be Wednesdays from 12-1 pm. emLab will provide lunch for everyone for the first month we are in-person and after that, it will transition to a brown bag lunch.*
- Zoom/remote meetings on in-person days
  - We work with lots of collaborators and partners around the world, so it is likely you may also have zoom calls on in-person days. Here are some options and suggestions for hybrid/zoom meetings:
    - MSI 1304 is available to reserve for zoom meetings - add bren-sfg@ucsb.edu to any calendar invite to reserve the room
    - Bren Hall has 7 conference rooms of varying sizes that you can book up to 14 days in advance.
    - For full details on MSI and Bren conference room sign-ups, see the [emLab manual](https://emlab-ucsb.github.io/emlab-manual/housekeeping.html#meeting-scheduling-and-logistics)
    - Call in via phone and take it outside/walking
    - If someone on the call has a solo office, plan to take the call from their office
    - Calls can also be taken from shared offices - everyone should have access to noise canceling headphones, so just give your office mates a heads up if you’re going to be jumping on a call/zoom.

*Hours and remote work*

- All team members are responsible for setting their own hours within the work week and getting their work done on time in coordination with their project teams.
  - Please use your google calendar to communicate to the team when you are not available during the work week.
  - Individuals are welcome to work, send emails, etc. outside of ‘normal’ working hours (e.g., nights and weekends) but immediate responses are not expected outside of normal working hours
- Ad hoc remote work may be permitted on a case-by-case basis. Contact your supervisor to discuss and get approval for ad hoc remote working days and communicate/coordinate with your project teams as needed. 

*Equipment and commuting*

- emLab will provide equipment for one workstation that will include: a laptop or desktop computer, a bluetooth keyboard and mouse, up to two computer monitors, and noise canceling headphones.
- emLab will also provide a desk and chair in your university office, and miscellaneous office supplies (notebooks, pens, etc.) as needed. 
  - Please notify your supervisor for approval and contact Erin to assist with re-allocation or purchasing if you need any of the items listed above.
- The University provides these resources ([TAP](https://www.tps.ucsb.edu/commuter-options)) for commuting to and from campus.

*Fully remote team members*

- emLab team members will be based at the UCSB campus unless you have a previously agreed-upon arrangement with your supervisor. Exceptions to this may be granted on an as-needed basis for projects requiring remote work.

*COVID protocols for working from the office*

- **Please do not come into the office if you are exhibiting any symptoms at all**, have recently been exposed to covid or are not feeling 100%. 
  - Information about where you can go for both asymptomatic and symptomatic testing is [here](https://www.ucsb.edu/COVID-19-information/testing).
- We will follow UCSB masking requirements and recommendations. The current policies and campus updates are posted [here](https://www.ucsb.edu/COVID-19-information/campus-updates#mitigation-protocols). Here is the current guidance:
  - Effective June 13, masks are no longer required but are strongly recommended in indoor spaces on campus, regardless of vaccination status, except when working alone in private offices. 
- All Santa Barbara-based employees must be fully vaccinated and have submitted proof of vaccination through the University [here](https://studenthealthoc.sa.ucsb.edu/login_dualauthentication.aspx) or have received an approved exemption before they will be allowed in any UC facility or office or to participate in any University programs.
- All employees must also complete the “COVID-19 Returning to Work” training course required by Cal/OSHA, which is available through the [UC Learning Center](https://t.e2ma.net/click/zgo54e/3j5nqn/3j1wix).
- Please abide by [University guidance related to COVID precautions](https://www.ucsb.edu/COVID-19-information) for in-office work and in-person meetings. 
- Cleaning materials and hand sanitizers will be available for office use.

*Guests and visitors*

- Guests and visitors should follow the University’s [COVID-19 interim visitor’s protocol](https://www.ucsb.edu/covid-19-information/return-to-campus-requirements/visitors-protocol#:~:text=Department%20and%20Invited%20Visitors,a%20rapid%20antigen%20home%20test.). A few key points:
  - Individuals invited to campus should be fully vaccinated against COVID-19 or have received a negative COVID-19 test result within 48 hours prior to their visit for a PCR test, or 24 hours prior for a rapid antigen home test. 
  - All visitors to campus are strongly recommended to wear face masks in any indoor space, and any individual who has symptoms suggestive of COVID-19 should avoid campus altogether. 
  - If you are unsure of a visitor’s vaccination status or prefer not to ask, you may send them the [on-demand screening survey](https://ucsb-641309.workflowcloud.com/forms/5f252a35-800a-4015-8256-ecd9b5c68a96) in advance to determine if they are cleared to be on campus and if and when they are required to test prior to arriving on campus, wear a mask or quarantine.

The health and safety of our team remains the most important thing above all else. As we learned these past couple of years, things can rapidly change, and we will continue to adapt as needed. If you do not feel safe coming into the office or if you have suggestions on additional measures that you would like to see in place, please come talk to me, any member of the Leadership Team, or your supervisor. Exceptions to these guidelines are permitted after they have been discussed and approved by your supervisor. 

Please reach out to your supervisor or any member of the leadership team if you have any questions.

*Last updated: August 17, 2022*

## Time management

It is important for every individual to understand and manage their workloads and responsibilities, and to ask for help when it is needed. Team members should prioritize the tasks that are most important and urgent. If you are having challenges prioritizing tasks, speak with your supervisor to discuss priorities.

emLab project staff are allocated to one or more projects, which is likely to shift over time as projects come to completion and new projects are launched. Staff should be aware of their general percentage time allocation across projects, which are tracked in the project tracking sheet in Drive. Due to the adaptive nature of our work, these percentages are likely to vary daily, weekly or monthly, and should be used as guidelines rather than strict allocations. If staff are feeling either underutilized or overstretched, they should speak with their supervisor.

## Project roles

**Principal Investigators**
Coming soon

**Research Staff**
Coming soon

**Project Managers**
Coming soon

**Postdoctoral Researchers**
Coming soon

**Graduate Students**
Coming soon

**Undergraduate Students**
Coming soon


## Meetings and events
emLab hosts a variety of events to foster a deep sense of community across roles and programs, and provide opportunities for our team to be as collaborative, functional, and fully integrated as possible. Each meeting or event aims to support the emLab mission of developing innovative insights and performing collaborative research, and supports one of the following objectives: facilitating research, building community, and informing & updating. 


We know things can come up that sometimes make it impossible to join everything, but we want to clarify that we do expect everyone to do their best to participate in team events, particularly the Tuesday Team Time meetings. Beyond that, if you find yourself with a lot on your plate, please use your discretion to decide when your participation will yield high returns, and do not feel obligated to participate in events that you don’t think will be a valuable use of your time. Each of us has unique interests, areas of expertise, and professional goals, and we trust that those will inform the decisions you make for yourself!

Events organizers include:

*emLab operations team*

- Executive Director - Michaela Clemence
- Program Manager - Erin O’Reilly
- Projects & Student Engagement Manager - Jennifer Bone
- Events & Project Manager - Heather Lahr
- Partnerships & Grants Manager - Annie Lovell

*Rotating faculty representatives (2023):*

- Andrew Plantinga
- Antony Millner

Here’s an overview of emLab events and the objectives of each, items with a * are highly encouraged:

**Meetings**

Meetings that facilitate the day-to-day workings on emLab. These serve as information conduits from leadership to staff as well as staff-to-staff support and collaboration. These are organized by the emLab operations team.

- *Tuesday Team Time (TTT) 
  - Who: emLab staff and postdocs
  - Cadence: weekly on Tuesdays
  - Structure: Learn about current work at emLab, celebrate successes, share team-wide announcements. 15 minute presentation by an emLab team member, 5 minutes of operational updates and announcements, and 10 minutes of team shoutouts, roundtable updates (on the     first Monday of the month), or mingling.
  - Detailed guidelines live [here](https://docs.google.com/document/d/1pDRWrrJXeecyF2jE2nIaWqX83x0VmDwVSrdqAbHKFrg/edit) and the schedule lives [here](https://docs.google.com/spreadsheets/d/18CCbR-YhboPHV_b-f5AHf0NQFxyQJ1R9fMWugcuXXtU/edit#gid=0)
  - POC: Events Manager
- Project Management Meetings
  - Who: Executive Director and project managers
  - Cadence: monthly on the second Tuesday of the month
  - Structure: Project managers fill our monthly status report prior to the meeting. Provide updates on the status of current projects, discuss challenges, and brainstorm solutions.
  - POC: Executive Director
- Quarterly fundraising update
  - Who: Executive Director and project and operations staff
  - Cadence: quarterly
  - Structure: Review funding pipeline and upcoming projects. 
  - POC: Partnerships & Grants Manager

**Community events**

Events geared towards community building and dissemination of information. 

- *Team lunches
  - Who: PIs, staff, postdocs, vistors
  - Cadence: monthly on the first Tuesday of the month
  - Aim: Monthly appreciation and collaboration catered lunches. This is a great time to share ideas and engage across the team.
  - POC: Partnerships & Grants Manager
- Happy hours
  - Who: PIs, staff, postdocs, visitors, students
  - Cadence: variable
  - Aim: Welcome new faces, celebrate successes, say goodbye to people transitioning away from emLab.
  - POC: Events Manager  
- emLab retreat
  - Who: PIs, staff, postdocs
  - Cadence: every 2 years
  - Aim: Foster collaboration, align priorities, look ahead to emLab goals, celebrate successes. 
  - POC: Executive Director/Program Manager
- Holiday celebration
  - Who: PIs, staff, postdocs, visitors, students
  - Cadence: annually in December
  - Typically hosted at a PI residence and may include gift exchange, games, and catered or potluck style food 
  - POC: Executive Director/Program Manager
  
**Academic events**

Events geared towards advancing current research, fostering collaboration, and networking to build stronger academics. These are organized by the Rotating Faculty Representatives and Events Manager. 

- Research roundtable
  - Who: emLab PIs, affiliates, postdocs, faculty collaborators
  - What: Weekly lunch meeting to present, discuss, debate, and refine ideas and research questions. Guidelines and schedule can be found [here](https://docs.google.com/document/d/1Y8ibvOyXaarqhs7Y2OKXyUQQyPYH82CIf99RYK7l6pU/edit). 
  - POC: Events Manager 
- Environmental Resource Economics (ERE) Seminars
  - Who: ERE Faculty, PhD students (bren, econ), postdocs, visitors
  - What: Joint seminar with the Economics department. Up to 8 invited speakers per academic year. Here is an [overview](https://docs.google.com/document/d/1UynPD0f034HedLyPx9TDBY39x4swqGV8yu_T0KtxNb4/edit) and [planning checklist](https://docs.google.com/document/d/19TPVWUq8jRTxqvetic5PquPUhnp6iCpMDrMkuudzb4I/edit).
  - POC: Events Manager 
- Occasional Workshop
  - What: Annual 1.5 day workshop for invited ERE researchers. Requires submission of papers and selection of presenters for full presentations and egg-timer presentations. Free registration for up to 100 total participants.
  - POC: Events Manager
- UC-EE seminars
  - What: Irregular remote seminars for 120+ UC Environmental, Energy and Natural Resource Economics faculty, postdoctoral scholars and graduate students. Requires addition to google group. Guidelines can be found [here](https://docs.google.com/document/d/1xHyvfdJVG48L8aKUkjxmB6H6saYprreN-4mTJSvZU6I/edit).
  - POC: Projects & Student Engagement Manager