---
title: "Housekeeping"
output: html_document
---

# Housekeeping

## Timekeeping

Every month, full-time Academic employees (Specialists, Academic Coordinators, Postdocs) accrue **8 hours of sick time and 16 hours of vacation.** You are responsible for making informed decisions about how to use your accruals (which you can find online at UCPath), but please notify your supervisor whenever you are out sick via slack or email, and let them and your teams know of any vacation time you plan to take well in advance so your projects and teams will run smoothly in your absence. More about requesting vacation in the next section

At the end of every month, you will need to fill out your timecard on [Kronos timekeeping system](https://timekeeping.ucsb.edu/). You only need to record any sick or vacation days you took (in increments of 8 hours), you do not need to record hours worked. This means that if you took no vacation or sick time in that month, you approve a blank timecard.  

Once you log in, make sure you are recording your hours in the “Previous Pay Period” (you can adjust this using the drop down menu at the top right-hand corner). On the days when you need to log hours, select “Vacation” or “Sick” under “Pay Code,” and enter “8” under “Amount.” We are not able to log anything less than one full day on this system (i.e., no half sick or vacation days). 

## Vacation

For vacations longer than five days, email your supervisor at least three weeks in advance of your planned time off outlining your dates and coordinate with your project teams to ensure that you will not be missing any critical deadlines or discuss how they can be covered by other project members. For shorter periods of time off (e.g., 1-2 days), aim to give your supervisor and project teams at least a few days notice. 

Please communicate with your team/s and use your calendar to note when you will be out of town, out of the office, or working remotely (and ensure your calendar is up to date).


## Meeting scheduling and logistics 

### Conference rooms

**Booking at MSI**

emLab MSI Suite (1304): add bren-sfg@ucsb.edu to any calendar invite to reserve the room. Add this same email address to your calendar to view availability. 

MSI conference rooms: bookings are centralized through the [MSI Room Request Form](https://docs.google.com/forms/d/e/1FAIpQLScCIMnaKQUXyw6_y7pfpDcPo8-ewYZKouNfgzWw27oCP3G8cQ/viewform). There are conference rooms available on the 2nd, 3rd, and 4th floors. Information about room capacity and technological capabilities are outlined [here](https://msi.ucsb.edu/index.php/administration/conference-room-information). This webpage also allows you to view room availability. If you have any questions, contact reservations@msi.ucsb.edu.

**Booking at Bren**

Most bookings are centralized through [booking.bren.ucsb.edu](http://booking.bren.ucsb.edu/). *Note: you are limited to booking up to 14 days ahead, no recurring meetings, and a max meeting length of two hours. Any requests that don't meet these limitations can still be booked through scheduling@bren.ucsb.edu.*

We can self-book the following rooms:

- Visitors Center (BH 1410)
- Bonsai (BH 4327)
- Manzanita (BH 4329)
- Oak (BH 1520)
- Sycamore (BH 1510)
- Maple (BH 3016)
- Pine (BH 3526)

Comprehensive details about amenities and seating are available on the [Bren website](https://bren.ucsb.edu/rooms).

Contact scheduling@bren.ucsb.edu if you would like to reserve the Dean’s Conference Room (BH 2436), Bren 1414 (large lecture hall), or Bren 1424 (larger seminar room/classroom).

Instructions for how to self-book rooms:

1. Visit [booking.bren.ucsb.edu](http://booking.bren.ucsb.edu/).
2. Click on “Schedule” in the upper left of the screen.
3. Select the date you want to meet (up to 14 days in advance).
4. Based upon which rooms are available, select the room and time you want by clicking in the corresponding area of the chart.
5. A box will open for you to enter the meeting details.
6. Type a title for your meeting (be sure to include your last name).
7. Select the end time (two hours maximum).
8. If you choose to invite guests, select them by typing their names or email addresses in the “Invite Guests” field.
9. Click “Book Now”.
10. Your meeting will appear on the chart. You can edit or cancel the meeting by clicking on the booking event and then clicking the three dots in the upper right corner.
11. If you want to see all the rooms you have reserved, click on “Upcoming”. You can edit and cancel reservations from here. 

### Hybrid meeting guidance

*Last updated July 2021*

As we transition back to the office, emLab will be testing out approaches to hybrid meetings to maintain inclusivity and maximize productivity as we will have folks who are both on and off campus. We hope to learn during this period when these meetings work well, when they don’t, and what could be improved to facilitate hybrid meetings. The following guidance should be considered for meetings during this transition period:

- All meetings should include a virtual conferencing option (zoom link ideally)
- All meeting materials, decisions, and follow up should be shared via email or slack. 
- Meeting hosts should verify and communicate who will be attending in-person and who will be attending remotely.
- For meetings that include both in-person and remote participants (aka, hybrid meetings):
  - If there are a couple of meeting attendees on campus and they want to zoom in together from an individual office, this is fine and can be coordinated individually.
  - For larger meetings or when no individual offices are available:
    - MSI 1304 has been set up with a stationary mac computer with a camera to log into Zoom. The room also has a microphone and a large screen. We think this is probably the best current set-up for larger team hybrid meetings in Bren and MSI.
      - To reserve the room, add bren-sfg@ucsb.edu to your meeting invitation 
    - In-person set-up in 1304:
      - Meeting hosts should designate themself or someone else to set up the equipment and monitor the zoom video and chat.
      - Designated person will log into the computer using the username and password on the sticker (sfg-totoaba and totoaba, respectively) and log into the Zoom meeting using their UCSB credentials.
      - At the end of the meeting, please log out of Zoom, but do not turn the computer off. 
    - In-person attendees:
      - Complete the daily screening to be cleared to be on campus. 
      - Optional, depending on room set-up, TBD by meeting host: Bring a laptop if they have one and join virtually from their own laptops without joining audio (note: this is different from muting yourself) to allow remote participants to be able to see people during the conversation.
  - When possible, meetings should leverage virtual technology for collaboration (jamboards, slides, Zoom whiteboard, etc)

## Catering

### Spending limits

The maximum rates allowed per person (including tax and tip) for entertainment are:

- Breakfast: $31
- Lunch: $54
- Dinner: $94
- Light Refreshment: $22 

### Catering options

There are two options for catering meals (aka getting them delivered) on campus:

1. Campus catering
2. Approved off-campus caterer 

*Note: these rules apply to off-site emLab events as well where food is being delivered.*

**Campus Catering**

If you want campus to cater your event, contact them at least 3 weeks in advance of your event so you can get on their schedule. They are very busy and their schedule usually fills up. To find out if Campus Catering is available for your event, fill out their [“Request a Proposal” form](https://www.dining.ucsb.edu/campus-catering/request-proposal) on their website.

You should be prepared to tell them when and where your event is, how many people you’ll need to feed, and what menu you have in mind. Campus catering menus can be found [here](https://www.dining.ucsb.edu/campus-catering/catering-menus).

**Approved off-campus caterers**

View a list of approved caterers here: [](https://www.ehs.ucsb.edu/caterers) (South Coast Deli is our normal go-to option). You have to select from this list if food is being **delivered** to campus. If you are picking up the food yourself, you do not need to select a restaurant off this list. 

**Catering permits**

If you are using a caterer other than Campus Catering, you may have to fill out a [Catering Permit](https://www.ehs.ucsb.edu/files/docs/rm/UCSBCateringPermit.pdf). You DO NOT need a permit for the following:

- Food being delivered to campus is less than $300 
- Pizza delivery
- If you are picking up food from a grocery store or restaurant

If you are requesting a permit, MSI Purchasing can help fill out the permit and distribute it to the necessary parties (Campus Catering, etc.) for approval. Ideally, this should be done a few days in advance of the event but they can expedite the process if under a time crunch.   

### Entertainment reimbursements

Entertainment reimbursements are centralized through [Concur](http://www.concursolutions.com/), where they are referred to as expense reports. See the Concur section below for more information. 

## Travel

Many of our projects require us to travel domestically and internationally. The University has various rules and procedures that are designed to (hopefully) make it as easy as possible for you to plan your trips, avoid covering expenses with your own money ahead of time, and easily get reimbursed for expenses you do incur while traveling. The [MSI travel page](https://msi.ucsb.edu/administration/travel) details information, rules, and restrictions for work-related travel.

### General travel guidelines

**Domestic travel**

Per UC policy, when traveling in the U.S. you can only be reimbursed up to $275/ night for lodging, and up to $62/day for meals and incidentals. If you exceed either maximum, know that you must cover the rest with your own funds. If you can’t find a hotel below $275/night, you will need to provide evidence of this (i.e. you must show proof of rates from other hotels in the nearby area that are higher than yours) to corroborate your claim that you got the cheapest available rate. Only then can you be reimbursed the full amount. There are no exceptions for exceeding the daily maximum for food.

You cannot be reimbursed for alcohol, so if you need to be reimbursed for a meal where alcohol was purchased, subtract the cost of the alcohol from the total you list on your reimbursement form. 

When you return from domestic travel, you will need to fill out an expense report in [Concur](http://www.concursolutions.com/) to be reimbursed for any expenses you incurred and paid for out-of-pocket while traveling. To be reimbursed for U.S. travel, you will need to submit an expense form with itemized receipts for all of your purchases – you cannot claim per diem for a domestic trip less than 30 days.

**International travel**

When you return from traveling outside of the country, you will need to fill out an expense report in [Concur](http://www.concursolutions.com/) to be reimbursed for any expenses you incurred while traveling. 

The most straightforward mechanism we recommend for reimbursing international travel is the State Department’s per diem rates, which are location-specific. On the [State Department’s website](https://aoprals.state.gov/web920/per_diem.asp), you can look up the country and city where you traveled to find the maximum daily lodging and food (M & IE) rates. The combined total of those two rates is the maximum allowable amount, per day of your trip, that you can be reimbursed. With per diem, you don’t have to submit receipts for lodging and food. For all other receipts (e.g. transportation) there is a built in currency conversion tool in Concur. 

### Paying for travel before you leave

There are two ways the University can pay for your travel expenses prior to your trip:

- **Travel Advances:** if you prefer to make your own reservations, might have to cancel/change your tickets, or plan to stay in non-traditional accommodations (e.g., AirBnb) you may have to pay for some of your travel expenses out of pocket before you go. Though you can’t submit a complete travel reimbursement form until after you return from your trip, you can get a partial reimbursement for expenses you cover prior to traveling by applying for a travel advance. 
  - Travel advances are processed through [Concur](http://www.concursolutions.com/). Once logged in, click on “Requests” and then the “Create a New Request” tile.
  - Fill out all of the information for your trip (name, dates, project code to charge, etc.). Once the general information has been submitted, you will be taken to a screen that allows you to insert line items for expenses you are requesting a travel advance for (e.g. conference registration, hotel). Once you insert the information, click on the line item(s) and then under “Request Details” click “Add Cash Advance.” View this [video](https://ucsb.service-now.com/kb?sys_kb_id=0d41a7dd1b3f745047e8ed34604bcb57&id=kb_article_view&sysparm_rank=2&sysparm_tsqueryId=5a6646a81bbdc51078889683b24bcb79) for visual instructions. 
  - Once a full draft of your request is ready, email Kim at MSI (kim.taylor@ucsb.edu) so she can review the request for compliance and completion. You submit the request after you get an ok from her. 
  - When you return, you will claim the amount you were given in your cash advance on your travel reimbursement expense form so that you don’t double count any expenditures. Watch [this video](https://ucsb.service-now.com/kb?sys_kb_id=7bc82fb41bc40150e9250f22604bcb87&id=kb_article_view&sysparm_rank=3&sysparm_tsqueryId=28d6022c1bbdc51078889683b24bcb74) for instructions on how to apply a cash advance in an expense report.
  
- **Concur Travel**: What was previously Connexxus is now housed within Concur and can be used to book flights, rental cars, or hotels. These reservations are directly billed to a University account, so there is no out-of-pocket cost. To book through the Travel tab in Concur:
  - Submit a request in Concur for your trip that includes the flight/hotel information and the project to charge. Ping Kim Taylor that you have a request ready for review.
  - Once Kim has approved your request, book your flight/hotel through the "Travel" tab in Concur. You charge this to the University credit card, not your own.

### Travel insurance

All employees and affiliates of the University are eligible for comprehensive trip insurance at no cost. This policy offers much more than just lost luggage replacement.

For example:

- If you are injured or become ill while travelling on University business, it covers all medical treatment/hospitalization costs, as well as any expenses for changed itineraries or modes of transport.  
- If you have to be extracted from your destination due to political violence or a weather-related emergency, all costs are covered.

If you book your travel through UC Travel/Connexxus, you are automatically enrolled in this coverage. Even if you paid for your travel yourself and submit a reimbursement after the fact, you can still get insurance coverage. You can register your trip [here](https://www.ucop.edu/risk-services-travel/registering.html).

### Travel reimbursements

Travel reimbursements are handled through [Concur](http://www.concursolutions.com/) and are filled out once you return from your trip. See the Concur section for further information.

### Visitor travel

There are some instances where we pay for visitor travel (e.g. emLab seminar speakers). Since they are not UCSB employees and thus do not have access to Concur, there are additional steps for the process. Instructions are outlined on the Concur Knowledge Base [here](https://ucsb.service-now.com/kb?sys_kb_id=6e60590b1b8a49908364a643b24bcb1c&id=kb_article_view&sysparm_rank=1&sysparm_tsqueryId=86a7d7451b22015078889683b24bcb8a) and copied below.

1. Fill out [this Request a New Guest Traveler form](https://ucsb.service-now.com/payment?id=paym_sc_cat_item&sys_id=842c406c47e9c9102e6808f2846d439a&sysparm_category=510d6ca7471909102e6808f2846d43e1) on the guests behalf.
2. Send the guest traveler a domestic or foreign [Guest Traveler Worksheet](https://drive.google.com/drive/folders/15DwJPiRELjSq7i16hAZDCTYF2lrp6HEQ?usp=sharing) to fill out.
3. Once the traveler has filled out the worksheet and provided all relevant receipts to the delegate, the delegate should begin creating the expense report for the guest traveler based on the submitted and signed worksheet.
4. Once the expense report is complete, save and close out. DO NOT submit the report yet. Notify donna.dobis@ucsb.edu or travel@bren.ucsb.edu that you have a draft expense report ready to review for compliance and completion. 
5. Once the expense report is submitted into the system and approved, a check is cut for the guest traveler. 

## Concur

[Concur](https://www.concursolutions.com/) is the University’s centralized platform for entertainment, travel, and miscellaneous reimbursements. This eliminates the previous need to fill out a paper reimbursement form. Erin can help answer Concur questions in addition to the following MSI and Bren staff:

- Kim Taylor (MSI; travel reimbursements) – kim.taylor@ucsb.edu
- Andrea Palmerin Del Toro and Trevor Bellefeuille (MSI; entertainment and business reimbursements) – purchasing@msi.ucsb.edu
- Phil Watt (Bren; travel, entertainment, and business reimbursements) – travel@bren.ucsb.edu or purchasing@bren.ucsb.edu

### Assigning delegates

One important step is setting up delegates in Concur. These are people who can draft expense reports on your behalf and/or review them for accuracy. Depending on the department you are charging, select delegates from the names listed above and anyone on the emLab team helping prepare your report. [This video](https://ucsb.service-now.com/kb?id=kb_article_view&sys_kb_id=a8df60ba1b348554e9250f22604bcba3) provides an overview of how to add delegates and the steps are listed below:

1. Once you are logged on to Concur, click on Profile in the upper right corner, and then Profile Settings.
2. Viewing the column of options on the left-hand side, locate and click on Expense Delegates. Please note; the ‘Request’ and ‘Expense’ categories share delegates. Permissions are assigned to both ‘Request’ and ‘Expense’ by selecting a delegate here.
3. Click Add.
4. Search for and select a delegate by employee name or email address.
5. Specify the delegate is to perform the following tasks, Can Prepare, Can Submit Requests, Can View Receipts, and Receive Emails. With these options selected, the delegate is allowed to prepare and submit requests, prepare expense reports on the traveler’s behalf, view receipts, and receive the same email notifications as the traveler.
6. After delegates have been established, click the Save to update the settings.

### Entertainment reimbursements

Once you have logged into Concur, follow these steps to prepare your expense report:

1. Click the Expense option from the top of the screen and then the “Create New Report” tile.
2. Fill out the fields listed on the report (e.g. event name, date, business purpose, etc.). 
    - Report type = entertainment
    - Event types are outlined [here](https://www.bfs.ucsb.edu/travel_entertainment/entertainment-reimbursement) by UCSB’s BFS. 
    - When filling out the Dept and FAU, be sure to select “Either” for the filter option so you see the correct options.
    - FAU = the project code. Note: you may have to enter the project code between stars (e.g. * EMS05Z *) for it to populate the search field.
    - Cost type = ENT
    - Sub account for entertainment = 3
3. Once the “metadata” for the report is created, you will be directed to a screen that allows you to add expenses. For each expense entry, fill out the relevant information and upload your receipt(s). Most of our entertainment reimbursements will fall under the “Business Meeting Exp. - Food, Rental, Supplies” expense type. 
4. For food purchases, you will have to add the attendees for the event. 
    - For Faculty/Staff: under the Attendees tab, select Faculty/Staff from the attendee type drop-down menu. Search their name within the system.
    - For other attendee types (students and guests): there are two ways to add other attendee types. The first is to create a new attendee and enter the prompted boxes. The second is to fill out the [attendee spreadsheet](https://www.concursolutions.com/Expense/Proxy/AttendeeExcelImport.asp?act=exceltemplate) and upload it (note: this will be easier when you have to add a lot of non-staff attendees).
5. Save and close out. DO NOT submit the report yet. Notify purchasing@msi.ucsb.edu or purchasing@bren.ucsb.edu that you have a draft expense report ready to review for compliance and completion. 
6. Submit a report ONLY after the Bren or MSI purchasing team notifies you to do so. 

### Travel reimbursements

Travel reimbursements are handled through [Concur](http://www.concursolutions.com/). Once you have logged into Concur, follow these steps to prepare your expense report:

1. Click the Expense option from the top of the screen and then the “Create New Report” tile.
2. Fill out the fields listed on the report (e.g. trip name, date, business purpose, etc.). 
    - Report type = Travel foreign, Travel in state, or Travel out of state
    - When filling out the Dept and FAU, be sure to select “Either” for the filter option so you see the correct options.
    - FAU = the project code. Note: you may have to enter the project code between stars (e.g. * EMS05Z *) for it to populate the search field. 
    - Cost type = TRV
    - Sub accounts: domestic travel = 5, foreign travel = 7
    - If you are claiming per diem for international travel, click “yes, I want to claim Travel Allowance” at the bottom of the page. Further details on claiming per diem are listed below.
3. Once the “metadata” for the report is created, you will be directed to a screen that allows you to add expenses. For each expense entry, fill out the relevant information and upload your receipt(s). 
4. Save and close out. DO NOT submit the report yet. Notify kim.taylor@ucsb.edu or travel@bren.ucsb.edu that you have a draft expense report ready to review for compliance and completion. 
5. Submit a report ONLY after the Bren or MSI purchasing team notifies you to do so.

**A note on claiming per diem for international travel**

Once you have noted that you are claiming per diem (and click next), you will be directed to a page where you input your travel itinerary. You need to include **every** step of your journey, including layovers. For example, if you left SB for LAX at 3:00pm on Friday, then your flight left LAX at 8:00pm, had a layover in Qatar, before going to your final destination, you will need to add trip details for each new location (SB, LAX, Qatar, final location) for both directions of travel (getting there, and getting home). 

Once all the dates are in place, you will be taken to a screen that allows you to note which days/meals you would like to claim per diem for. With this method, you will not have to add individual receipts to your expense report. Note that you cannot claim foreign per diem for meals while you are still in America. You will have to keep those receipts and log them independently OR “trick” the system by selecting a higher per diem on a day when you were out of the country. For example, if per diem for food is $134, and you spent $20 at the airport but didn’t pay for breakfast during your international trip, you can just choose a breakfast per diem while you were overseas instead of logging the airport receipt.

When selecting per diem meals: you will be able to select breakfast, lunch, and dinner per diem (checking a box will mean that you are not claiming that meal/day). Try to find the per diem value that most accurately reflects how much money you spent on meals during the trip (+ anything else you spent and couldn’t get receipts for - like taxis). 

### Concur/reimbursement quirks

Since this is a new platform (as of February 2022), we are continually updating our instructions. Some things we have learned:

- If your hotel/lodging was covered by a separate entity, the University still wants proof that you were there. Fill out an expense line item for $0 that includes lodging confirmation as the receipt.
- For domestic travel, you can fill out a [meal log](https://docs.google.com/document/d/1gVmnw7V4wJQ4cxs-IDWVNLFro1ZyaGndkSrEbqxFNpQ/edit?usp=sharing) instead of uploading each meal receipt separately. *Note: Bren allows this, sometimes MSI wants the receipts*. If you go the meal log route:
  - Fill out the form with expenses per day.
  - Create a meals expense line in Concur and upload the meal log as your receipt.
  - Itemize the meal log across the different days. You will be prompted to do this by Concur. 
