---
title: "emLab Manual"
author: ""
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
github-repo: emlab-ucsb/emlab-manual
url: "https://github.com/emlab-ucsb/emlab-manual"
description: "Everything you need to know about emLab."
#cover-image: "" If there's a png we want to use, it can go here
---

# Welcome

Hello and welcome to our team manual! 

This is the lab manual for the Environmental Markets Lab (emLab) at the University of California Santa Barbara.

We are a tightly knit team of faculty, researchers, project managers, post-docs, and students dedicated to informing market-based approaches for environmental and social good. emLab fosters a collaborative work environment to unite interdisciplinary expertise with the collective goal of solving critical environmental problems. We are a team of intellectual go-getters: eager to tackle new challenges and think outside the box to support a healthy environment that can sustain generations to come. You can read more about our research and projects on our [website](https://emlab.msi.ucsb.edu/). 

This manual provides an overview of who we are and sets expectations and provides resources on how we work. This is the place where we centralize team resources, information about team procedures, and document institutional knowledge so we can work more effectively together.

If you have any suggestions for additions or edits, please email us at [emlab-ops@googlegroups.com](mailto:emlab-ops@googlegroups.com). 

*Our lab manual is inspired by and draws on the [Faylab lab manual](https://thefaylab.github.io/lab-manual/). We appreciate their leadership and dedication to creating open source resources to improve open science and transparency.* 
